/**
 * Admin sign-up — invite-token based.
 *
 * Flow:
 *  1. Recipient opens `/admin/signup?token=…` (link sent by a super admin)
 *  2. Page validates the token via GET /api/admin/auth/signup/:token
 *  3. Email + role are pre-filled and locked (the invite chose them); the
 *     user picks a display name + password and submits.
 *  4. POST /api/admin/auth/signup consumes the token, creates the admin,
 *     issues a session — we drop straight into /admin.
 *
 * Open sign-up is intentionally not available. To get an account you need a
 * fresh invite link from an existing super admin.
 */
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { adminInvitePreview, adminSignup } from '../../api/adminApi.js';
import { useAdmin } from '../../providers/AdminProvider.jsx';
import {
  IconShield, IconLightning, IconActivity, IconSparkles, IconArrowRight,
  IconKey, IconCheck, IconAlert, IconLogout,
} from '../../components/admin/Icons.jsx';

const ROLE_LABEL = {
  super_admin:   'Super admin',
  finance_admin: 'Finance lead',
  odds_manager:  'Trading desk',
  support:       'Support agent',
  moderator:     'Risk & moderation',
};

const ROLE_BLURB = {
  super_admin:   'Unrestricted. Can grant or revoke other admins.',
  finance_admin: 'Withdrawals, refunds, wallet adjustments, financial reports.',
  odds_manager:  'Fixtures, markets, live odds intervention, manual settlement.',
  support:       'Read-only access to players + bets, ticket replies.',
  moderator:     'Bans, suspensions, KYC, fraud flags.',
};

export default function AdminSignup() {
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const { admin, signIn, theme } = useAdmin();

  const token = params.get('token') || '';
  const [invite, setInvite] = useState(null);
  const [validating, setValidating] = useState(true);
  const [tokenError, setTokenError] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [password, setPassword]       = useState('');
  const [confirm, setConfirm]         = useState('');
  const [busy, setBusy] = useState(false);
  const [err, setErr]   = useState('');

  useEffect(() => {
    if (admin) {
      // Already signed in — bounce to the dashboard, no need to consume an invite.
      navigate('/admin', { replace: true });
    }
  }, [admin, navigate]);

  useEffect(() => {
    if (!token) {
      setValidating(false);
      setTokenError('No invite token provided. Sign-up is invite-only.');
      return;
    }
    let alive = true;
    setValidating(true);
    adminInvitePreview(token).then((inv) => {
      if (!alive) return;
      setInvite(inv);
      setDisplayName(inv.displayName || '');
      setTokenError('');
    }).catch((e) => {
      if (!alive) return;
      setTokenError(e.message || 'Invite link is invalid, expired, or already used.');
    }).finally(() => alive && setValidating(false));
    return () => { alive = false; };
  }, [token]);

  const passwordOk = useMemo(() => {
    return password.length >= 8
      && /[A-Z]/.test(password)
      && /[a-z]/.test(password)
      && /\d/.test(password);
  }, [password]);
  const passwordsMatch = password.length > 0 && password === confirm;

  async function submit(e) {
    e.preventDefault();
    setErr('');
    if (!passwordOk) { setErr('Use at least 8 chars, mixing upper, lower and a number.'); return; }
    if (!passwordsMatch) { setErr('The two passwords do not match.'); return; }
    setBusy(true);
    try {
      const res = await adminSignup({ token, displayName: displayName.trim(), password });
      signIn(res);
      navigate('/admin', { replace: true });
    } catch (e) {
      setErr(e.message || 'Sign-up failed.');
    } finally { setBusy(false); }
  }

  return (
    <div data-admin-root data-theme={theme} className="adm-auth">
      <aside className="adm-auth-art">
        <span className="glow" />
        <div>
          <div className="feature"><IconShield size={14} /> Invite only · audited on issue + use</div>
          <h1>Activate your admin account.</h1>
          <p style={{ marginBottom: 28 }}>
            Admin sign-up is invite-only by design. Your link was generated by a super admin and is tied to
            a specific email and role. Once you complete this form the invite is burnt — it can't be reused.
          </p>
          <div style={{ display: 'grid', gap: 14 }}>
            {[
              { icon: <IconKey size={16} />,        t: 'Hardened auth',  d: 'Bcrypt @ 12 rounds. 2FA available post-signup.' },
              { icon: <IconLightning size={16} />,  t: 'Scoped role',    d: 'Your invite ties to one of five admin roles.' },
              { icon: <IconActivity size={16} />,   t: 'Every action audited', d: 'IP, user agent, before/after — all signed.' },
            ].map((f) => (
              <div key={f.t} style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <span style={{ width: 34, height: 34, borderRadius: 10, display: 'inline-grid', placeItems: 'center', background: 'rgba(255,255,255,.08)', border: '1px solid rgba(255,255,255,.12)', color: 'rgba(255,255,255,.92)' }}>{f.icon}</span>
                <div>
                  <div style={{ fontWeight: 700, fontSize: 14 }}>{f.t}</div>
                  <div style={{ color: 'rgba(255,255,255,.62)', fontSize: 12.5 }}>{f.d}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div style={{ fontSize: 12, color: 'rgba(255,255,255,.5)' }}>
          © {new Date().getFullYear()} Xenbet Gaming · Licensed by the Gaming Commission of Ghana
        </div>
      </aside>

      <section className="adm-auth-form">
        <div className="form-card">
          <h2>Create your admin account</h2>
          <p className="lead">
            {invite
              ? `Your invite is ready. Pick a display name and a strong password.`
              : `We'll validate your invite token then ask for a password.`}
          </p>

          {validating && (
            <div className="adm-loading"><span className="adm-spinner" /> Validating invite…</div>
          )}

          {!validating && tokenError && (
            <>
              <div className="err" style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <IconAlert size={16} /> {tokenError}
              </div>
              <div style={{ marginTop: 18, padding: 14, border: '1px dashed var(--border)', borderRadius: 12, background: 'var(--surface-soft)', fontSize: 13, color: 'var(--text-dim)' }}>
                <strong style={{ color: 'var(--text)' }}>Need access?</strong> Ask any existing super admin to issue you a new invite from{' '}
                <em>Settings → Admin invites</em>. Invites expire after 7 days by default.
              </div>
              <div style={{ marginTop: 18, display: 'flex', justifyContent: 'space-between' }}>
                <Link to="/" style={{ color: 'var(--text-soft)', fontSize: 13 }}>← Back to site</Link>
                <Link to="/admin/login" style={{ color: 'var(--text)', fontSize: 13, fontWeight: 600 }}>Already have an account? Sign in</Link>
              </div>
            </>
          )}

          {!validating && invite && (
            <form onSubmit={submit} className="form-grid">
              {err && <div className="err">{err}</div>}

              <div className="adm-field">
                <label>Email</label>
                <input className="adm-input" value={invite.email} readOnly tabIndex={-1}
                       style={{ opacity: .85, cursor: 'not-allowed' }} />
              </div>

              <div className="adm-field">
                <label>Role · assigned by your invite</label>
                <div style={{
                  padding: '10px 12px',
                  background: 'var(--surface-soft)',
                  border: '1px solid var(--border)',
                  borderRadius: 10,
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <strong>{ROLE_LABEL[invite.adminRole] || invite.adminRole}</strong>
                    <span style={{ fontSize: 11, letterSpacing: '.12em', color: 'var(--text-dim)', textTransform: 'uppercase', fontWeight: 700 }}>{invite.adminRole}</span>
                  </div>
                  <div style={{ marginTop: 4, fontSize: 12.5, color: 'var(--text-dim)' }}>
                    {ROLE_BLURB[invite.adminRole] || '—'}
                  </div>
                </div>
              </div>

              <div className="adm-field">
                <label htmlFor="su-name">Display name</label>
                <input id="su-name" className="adm-input" value={displayName}
                       onChange={(e) => setDisplayName(e.target.value)}
                       minLength={2} maxLength={60} required autoFocus
                       placeholder="e.g. Akua Mensah" />
              </div>

              <div className="adm-field">
                <label htmlFor="su-pw">Password</label>
                <input id="su-pw" className="adm-input" type="password"
                       autoComplete="new-password"
                       value={password} onChange={(e) => setPassword(e.target.value)} required minLength={8} />
                <PasswordHints password={password} ok={passwordOk} />
              </div>

              <div className="adm-field">
                <label htmlFor="su-pw2">Confirm password</label>
                <input id="su-pw2" className="adm-input" type="password"
                       autoComplete="new-password"
                       value={confirm} onChange={(e) => setConfirm(e.target.value)} required minLength={8}
                       style={confirm && !passwordsMatch ? { borderColor: 'var(--danger)' } : undefined} />
                {confirm && !passwordsMatch && (
                  <span style={{ color: 'var(--danger)', fontSize: 12 }}>Passwords don't match.</span>
                )}
              </div>

              <button type="submit" className="adm-btn primary" disabled={busy || !passwordOk || !passwordsMatch}
                      style={{ justifyContent: 'center', height: 44 }}>
                {busy ? 'Creating account…' : <>Create admin account <IconArrowRight size={16} /></>}
              </button>

              <div className="smol" style={{ display: 'flex', justifyContent: 'space-between' }}>
                <Link to="/" style={{ color: 'var(--text-soft)' }}>← Back to site</Link>
                <Link to="/admin/login" style={{ color: 'var(--text)' }}>Already have an account? Sign in</Link>
              </div>
              <div style={{ fontSize: 11, color: 'var(--text-mute)', textAlign: 'center', marginTop: 6 }}>
                Invite expires {invite.expiresAt ? new Date(invite.expiresAt).toLocaleString() : '—'}
              </div>
            </form>
          )}
        </div>
      </section>
    </div>
  );
}

function PasswordHints({ password, ok }) {
  const tests = [
    { label: '8+ characters', pass: password.length >= 8 },
    { label: 'Upper + lower case', pass: /[A-Z]/.test(password) && /[a-z]/.test(password) },
    { label: 'A number', pass: /\d/.test(password) },
  ];
  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 4 }}>
      {tests.map((t) => (
        <span key={t.label} style={{
          display: 'inline-flex', alignItems: 'center', gap: 4,
          fontSize: 11, padding: '3px 8px', borderRadius: 999,
          background: t.pass ? 'rgba(24,240,161,.12)' : 'var(--surface-soft)',
          color: t.pass ? 'var(--accent)' : 'var(--text-dim)',
          border: `1px solid ${t.pass ? 'rgba(24,240,161,.24)' : 'var(--border)'}`,
        }}>
          {t.pass ? <IconCheck size={11} /> : <IconAlert size={11} />} {t.label}
        </span>
      ))}
    </div>
  );
}
